<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAHsxIJE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAHsxIJE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAHsxIJE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAHsxIJE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAHsxIJE\App_KernelDevDebugContainer([
    'container.build_hash' => 'AHsxIJE',
    'container.build_id' => '15f90bf7',
    'container.build_time' => 1593262604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAHsxIJE');
